# =========================================
# User Service 本地开发配置
# =========================================
server:
  port: 8083  # 本地启动端口
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.3&characterEncoding=UTF-8&useUnicode=true
    username: Klisor
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: UserHikariPool
      maximum-pool-size: 15
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.zjsu.nsq.user: DEBUG
    org.hibernate.SQL: DEBUG